### ISSUE TITLE
Module build failed: TypeError

### ISSUE THREAD

**Issue by xinshouke** [vuejs/vue-hackernews#34]
My platform win10/node v6.1,The errors was throw after executed npm run build/dev:
ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/NewsView.vue
Module build failed: TypeError: E:\hotel\vue-hackernews-gh-pages\src\components\NewsView.vue:102:1
    98|     a
    99|       margin-right 10px
   100|       &:hover
   101|         text-decoration underline
   102|
--------^

Path must be a string. Received undefined

```
at assertPath (path.js:7:11)
at extname (path.js:887:5)
at new SourceMapper (E:\hotel\vue-hackernews-gh-pages\node_modules\stylus\lib\visitor\sourcemapper.js:41:7)
at Renderer.render (E:\hotel\vue-hackernews-gh-pages\node_modules\stylus\lib\renderer.js:94:9)
at E:\hotel\vue-hackernews-gh-pages\node_modules\stylus-loader\index.js:149:12
at tryCatchReject (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:840:30)
at runContinuation1 (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:799:4)
at Fulfilled.when (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:590:4)
at Pending.run (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:481:13)
at Scheduler._drain (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\Scheduler.js:62:19)
at Scheduler.drain (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\Scheduler.js:27:9)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
```

 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/NewsView.vue 4:14-247

ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/App.vue
Module build failed: TypeError: E:\hotel\vue-hackernews-gh-pages\src\components\App.vue:93:1
   89|   html, body
   90|     margin 0
   91|   #wrapper
   92|     width 100%
   93|
-------^

Path must be a string. Received undefined

```
at assertPath (path.js:7:11)
at extname (path.js:887:5)
at new SourceMapper (E:\hotel\vue-hackernews-gh-pages\node_modules\stylus\lib\visitor\sourcemapper.js:41:7)
at Renderer.render (E:\hotel\vue-hackernews-gh-pages\node_modules\stylus\lib\renderer.js:94:9)
at E:\hotel\vue-hackernews-gh-pages\node_modules\stylus-loader\index.js:149:12
at tryCatchReject (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:840:30)
at runContinuation1 (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:799:4)
at Fulfilled.when (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:590:4)
at Pending.run (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:481:13)
at Scheduler._drain (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\Scheduler.js:62:19)
at Scheduler.drain (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\Scheduler.js:27:9)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
```

 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/App.vue 4:14-242

ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/ItemView.vue
Module build failed: TypeError: E:\hotel\vue-hackernews-gh-pages\src\components\ItemView.vue:96:1
   92|     margin-top 0
   93|     margin-bottom 30px
   94|   .itemtext p
   95|     margin 10px 0
   96|
-------^

Path must be a string. Received undefined

```
at assertPath (path.js:7:11)
at extname (path.js:887:5)
at new SourceMapper (E:\hotel\vue-hackernews-gh-pages\node_modules\stylus\lib\visitor\sourcemapper.js:41:7)
at Renderer.render (E:\hotel\vue-hackernews-gh-pages\node_modules\stylus\lib\renderer.js:94:9)
at E:\hotel\vue-hackernews-gh-pages\node_modules\stylus-loader\index.js:149:12
at tryCatchReject (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:840:30)
at runContinuation1 (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:799:4)
at Fulfilled.when (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:590:4)
at Pending.run (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:481:13)
at Scheduler._drain (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\Scheduler.js:62:19)
at Scheduler.drain (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\Scheduler.js:27:9)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
```

 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/ItemView.vue 4:14-247

ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/UserView.vue
Module build failed: TypeError: E:\hotel\vue-hackernews-gh-pages\src\components\UserView.vue:61:1
   57|   .about
   58|     margin-top 1em
   59|   .links a
   60|     text-decoration underline
   61|
-------^

Path must be a string. Received undefined

```
at assertPath (path.js:7:11)
at extname (path.js:887:5)
at new SourceMapper (E:\hotel\vue-hackernews-gh-pages\node_modules\stylus\lib\visitor\sourcemapper.js:41:7)
at Renderer.render (E:\hotel\vue-hackernews-gh-pages\node_modules\stylus\lib\renderer.js:94:9)
at E:\hotel\vue-hackernews-gh-pages\node_modules\stylus-loader\index.js:149:12
at tryCatchReject (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:840:30)
at runContinuation1 (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:799:4)
at Fulfilled.when (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:590:4)
at Pending.run (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\makePromise.js:481:13)
at Scheduler._drain (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\Scheduler.js:62:19)
at Scheduler.drain (E:\hotel\vue-hackernews-gh-pages\node_modules\when\lib\Scheduler.js:27:9)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
```

 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/UserView.vue 4:14-247

**Comment by yyx990803** [comment]
This is a stylus-loader bug in Node 6. Use Node 5 before it's fixed.
