### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by thany** [vuejs/vue-hackernews#35]
Downloaded the zip, ran `npm install`, ran `npm run dev`. That's all I did.

Then, this error:

```
ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/NewsView.vue
Module build failed: TypeError: d:\Klanten\vue-loader-example\src\components\NewsView.vue:102:1
    98|     a
    99|       margin-right 10px
   100|       &:hover
   101|         text-decoration underline
   102|
--------^

Path must be a string. Received undefined

    at assertPath (path.js:7:11)
    at extname (path.js:887:5)
    at new SourceMapper (D:\Klanten\vue-loader-example\node_modules\stylus\lib\visitor\sourcemapper.js:41:7)
    at Renderer.render (D:\Klanten\vue-loader-example\node_modules\stylus\lib\renderer.js:94:9)
    at D:\Klanten\vue-loader-example\node_modules\stylus-loader\index.js:149:12
    at tryCatchReject (D:\Klanten\vue-loader-example\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (D:\Klanten\vue-loader-example\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (D:\Klanten\vue-loader-example\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (D:\Klanten\vue-loader-example\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (D:\Klanten\vue-loader-example\node_modules\when\lib\Scheduler.js:62:19)
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/NewsView.vue 4:14-257 13:2-17:4 14:20-263
```

This error repeats for every block of stylus code.

If I convert it to css, it's fine. So it looks as if it's missing a module or something.

**Comment by yyx990803** [comment]
This is a stylus-loader bug in Node 6. Use Node 5 until it's fixed.

**Comment by noahmatisoff** [comment]
Still unresolved?

**Comment by chogarcia** [comment]
This is still happening for me, and even with Node 5

**Comment by jiv-e** [comment]
I had a typo in my component file's style tag.

`<style scoped land="scss">`

Fixed this with:

`<style scoped lang="scss">`

Hope this helps.
