### ISSUE TITLE
won't start in production or dev

### ISSUE THREAD

**Issue by janat08** [vuejs/vue-hackernews#47]
running in dev fails like this
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

trying to start in production fails so
cross-env NODE_ENV=production webpack --config build/webpack.client.config.js --progress --hide-modules

**Comment by yyx990803** [comment]
Make sure to use Node 6+.
