### ISSUE TITLE
npm  run build  Error

### ISSUE THREAD

**Issue by LBX13** [vuejs/vue-hackernews#52]
vue-hackernews@1.0.0 build C:\Users\v_liubingxue\Downloads\vue-hackernews-gh-pages
> cross-env NODE_ENV=production webpack --progress --hide-modules

Hash: 60e1b7e993d9b77d1124ts\
Version: webpack 1.15.0
Time: 18201ms
   Asset    Size  Chunks             Chunk Names
build.js  104 kB       0  [emitted]  main

ERROR in ./src/components/App.vue
Module build failed: TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.module.exports (C:\Users\v_liubingxue\Downloads\vue-hackernews-gh-pages\node_modules\vue-loader\lib\loader.js:32:24)
 @ ./src/main.js 13:11-42

ERROR in ./src/components/NewsView.vue
Module build failed: TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.module.exports (C:\Users\v_liubingxue\Downloads\vue-hackernews-gh-pages\node_modules\vue-loader\lib\loader.js:32:24)
 @ ./src/main.js 17:16-52

ERROR in ./src/components/ItemView.vue
Module build failed: TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.module.exports (C:\Users\v_liubingxue\Downloads\vue-hackernews-gh-pages\node_modules\vue-loader\lib\loader.js:32:24)
 @ ./src/main.js 21:16-52

ERROR in ./src/components/UserView.vue
Module build failed: TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.module.exports (C:\Users\v_liubingxue\Downloads\vue-hackernews-gh-pages\node_modules\vue-loader\lib\loader.js:32:24)
 @ ./src/main.js 25:16-52

**Comment by yyx990803** [comment]
Your Node version is too old.
